tosca_definitions_version: tosca_simple_yaml_1_0

description: Some basic fixtures

imports:
   - custom_types/xos.yaml

topology_template:
  node_templates:
    m1.large:
      type: tosca.nodes.Flavor

    m1.medium:
      type: tosca.nodes.Flavor

    m1.small:
      type: tosca.nodes.Flavor

    m1.xlarge:
      type: tosca.nodes.Flavor

    MyDeployment:
      type: tosca.nodes.Deployment
      requirements:
          - m1.xlarge:
             node: m1.large
             relationship: tosca.relationships.SupportsFlavor
          - m1.large:
             node: m1.large
             relationship: tosca.relationships.SupportsFlavor
          - m1.medium:
             node: m1.medium
             relationship: tosca.relationships.SupportsFlavor
          - m1.small:
             node: m1.small
             relationship: tosca.relationships.SupportsFlavor

    mysite:
      type: tosca.nodes.Site
      properties:
          display_name: MySite
      requirements:
          - deployment:
               node: MyDeployment
               relationship: tosca.relationships.SiteDeployment

    # Attach the Tenant view to the MyDeployment deployment
    Tenant:
      type: tosca.nodes.DashboardView
      properties:
          no-create: true
          no-delete: true
      requirements:
          - deployment:
              node: MyDeployment
              relationship: tosca.relationships.SupportsDeployment

    padmin@vicci.org:
      type: tosca.nodes.User
      properties:
          password: letmein
#          encrypted_password: pbkdf2_sha256$12000$Qufx9iqtaYma$xs0YurPOcj9qYQna/Qrb3K+im9Yr2XEVr0J4Kqek7AE=
          firstname: XOS
          lastname: admin
          is_admin: true
      requirements:
          - site:
              node: mysite
              relationship: tosca.relationships.MemberOfSite
          - tenant_dashboard:
              node: Tenant
              relationship: tosca.relationships.UsesDashboard



